### ISSUE TITLE
[Suggestion] Keyboard Shortcut?

### ISSUE THREAD

**Issue by ibehnam** [Maluen/code-medium#13]
This extension is exactly what I was looking for! Thanks for doing this. I was wondering if we can assign shortcut keys to insert Github Gists using this extension? Medium already has some for text (e.g., CMD+OPTION+1 => Heading 1). It'd be nice to have something like CMD+OPT+0 => Insert Gist.

**Comment by Maluen** [comment]
This does indeed looks nice to have. I think the user should be able to customize the shortcut, maybe even keeping "CMD/CTRL + OPTION" and just changing "1" with other keys.

The customization could be done in the extension button popup.

The user should also know that they can use the shortcut, so the info should be added somewhere, in the list of features but also potentially in the gist editor as a tip.

**Comment by ibehnam** [comment]
Yes, that all sounds good!

If it's not possible to do, there's always the option of assigning shortcuts in the browser (e.g., in Brave you can assign shortcuts to extensions, but the extension has to provide the list of its functionalities, see the Dark Reader example).

For example, the following doesn't work:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/58621210/180470729-6312fb3e-ad69-44f5-882e-cda5efcab96e.png">

But this one works:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/58621210/180470797-a78568e4-85cc-4d3a-a4ba-5d89455f9104.png">

**Comment by Maluen** [comment]
Added shortcut with default "CTRL/CMD + SHIFT + 0".

I didn't use "CTRL/CMD + ALT/OPT + 0" since chrome allows either "CTRL" or "ALT". See https://developer.chrome.com/docs/extensions/reference/commands/#key-combinations

If another extension is already using the same combination, the shortcut will be unset and must be manually changed. This can be confusing for an end user. For this chrome docs suggest notifying the user on installation, example: https://developer.chrome.com/docs/extensions/reference/commands/#verify-commands-registered

For now no notification is being shown.

**Comment by Maluen** [comment]
I've changed the default to "ALT + SHIFT + 0" as the old one triggered zoom in Firefox, also other "CTRL + SHIFT" combinations are bound to firefox's own shortcuts.

**Comment by Maluen** [comment]
Also the shortcut will only work when the Medium Editor toolbar is active, that is when the cursor is on a new line (most of the time this also means the "+" is visible):

![image](https://user-images.githubusercontent.com/1434239/180603197-7b9bdd4b-7114-4f11-926a-20a91c326638.png)

Otherwise it wouldn't add the gist anyway after typing it.

**Comment by ibehnam** [comment]
Thanks @Maluen for this!  I haven't got the chance to download the files to update the extension yet, and the one on the Chrome store (and the release page here) is outdated. I'll give it a shot first chance I get and will let you know how it is.

**Comment by Maluen** [comment]
@ibehnam I didn't release yet, but you can build from source to test latest commits. See https://github.com/Maluen/code-medium#building-manually the generated folder can be loaded as an "unpacked extension" in chrome/firefox.

**Comment by ibehnam** [comment]
Thanks! I missed the part about building. Had tried just importing the SRC
folder in Chrome but got the “manifest is corrupted” error. Will try again.

**Comment by Maluen** [comment]
@ibehnam the folder to load is `dist/chrome` (in Chrome) or `dist/firefox` (in Firefox), which is generated by following https://github.com/Maluen/code-medium#building-manually

**Comment by Maluen** [comment]
Done, included in v0.6.0
