### ISSUE TITLE
Code blocks are being created with a fixed height

### ISSUE THREAD

**Issue by gustavo-depaula** [Maluen/code-medium#3]
It seems that every code block is being created with a fixed height. Small blocks get extra padding at the bottom:
![image](https://user-images.githubusercontent.com/732422/63228458-9130ea00-c1c9-11e9-870d-02d74bf60e5c.png)
and large blocks get cut:
![image](https://user-images.githubusercontent.com/732422/63228468-be7d9800-c1c9-11e9-89f8-bd6e4859e140.png)

**Comment by Maluen** [comment]
I don't think this has anything to do with the extension itself, the dispayed code is handled directly by Medium.

Don't you get the same when pasting directly a gist URL created without the extension (with "add an embed" button)?

**Comment by Maluen** [comment]
Yes, I tried with a new gist created without the extension, disabled the extension completely and added the gist in a new article. It still shows the bug, so it must be a Medium issue.

By the way, the problem is only visible in the editor itself. For example viewing the draft link shows the full gist.

**Comment by Maluen** [comment]
It would be nice if the extension would be able to fix this issue.

Basically the problem seems to be that Medium doesn't know the iframe height and thus just uses a fixed height.

In the other end, in the draft / published link uses the correct height, probably Medium calculates it when creating the link.

**Comment by gustavo-depaula** [comment]
oh!
thanks for the answer!
it makes sense to me, i'll close the issue then

**Comment by Maluen** [comment]
I've just published version 0.4.0 to chrome & firefox extension stores.

It detects the code block real height and sets it accordingly so that there are no extra padding and the content is displayed fully.

It is possible that Medium will fix the bug themselves in the future, in this case we can just remove this feature if needed.

**Comment by esr360** [comment]
@Maluen amazing!

What's interesting is that this wasn't an issue with Medium until only a few months ago. It was working fine, then they broke it, and never bothered to fix it.
