### ISSUE TITLE
Security-untrustful GitHub login window

### ISSUE THREAD

**Issue by iirekm** [Maluen/code-medium#5]
When I install the extension and click "GitHub login" a popup window appears asking for GitHub credentials. The popup window doesn't have an addressbar, F11 (page inspect) doesn't work. How can I know it's real, not phished GitHub login window?

And also: IMHO this windows shouldn't even appear at all, I'm already logged in to GitHub, the extension could simply use cookie.

Browser: Chrome
OS: Kubuntu 20

**Comment by Maluen** [comment]
>And also: IMHO this windows shouldn't even appear at all, I'm already logged in to GitHub, the extension could simply use cookie.

The extension needs to use OAUTH to get an access token that can be used to interact with the Github API in behalf of the user, so that it can create gists. See https://developer.github.com/v3/#authentication

If you don't trust it, you can review the source code and install it from source.

It uses standard WebExtension API to handle OAUTH authentication. You can check the file here: https://github.com/Maluen/code-medium/blob/master/src/background/services/AuthService.js

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/identity/launchWebAuthFlow used to launch the OAUTH window ("popup window").
- https://github.com/login/oauth/access_token is called to get the access token
- The access token is stored in local storage of the extension: https://github.com/Maluen/code-medium/blob/master/src/background/services/AuthService.js#L119

**Comment by Maluen** [comment]
Closing because of no response. Open a new issue if you have futher questions or need clarifications.
